s={1,2,3,4,5}
s1={1,2,3,6,7}
print(s.difference(s1))
print(s.intersection(s1))
print(s.isdisjoint(s1))
print(s.issubset(s1))
print(s.issuperset(s1))
print(s.union(s1))
print(s.symmetric_difference(s1))
print(s.copy())
s={1,2,3,4,5}
s.difference_update(s1)
print(s)
s.intersection_update(s1)
print(s)
s.symmetric_difference_update(s1)
print(s)