import tkinter

win=tkinter.Tk()

# def data():
#     text1=e1.get()
#     print(text1)
#     l2.config(text=text1)
#     l2.pack()

def data2():
    text1=v1.get()
    text2=v2.get()
    text3=v3.get()
    print(text1,text2,text3)
win.title('synnefo')
win.geometry('200x150')
win.minsize(100,100)
win.maxsize(500,500)
win.config(background='blue')
# l1=tkinter.Label(win,text='WELCOME TO ALL')
# l1.pack()
# l1.grid(row=0,colum=0)
# e1=tkinter.Entry(win,background='black',foreground='white')
# e1.pack()
# b1=tkinter.Button(win,text='submit',command=data)
# b1.pack()
v1=tkinter.IntVar()
v2=tkinter.IntVar()
v3=tkinter.IntVar()
l4=tkinter.Label(text='ENGLISH')
l4.pack()
c1=tkinter.Checkbutton(win,variable=v1)
c1.pack()
l3=tkinter.Label(text='MALAYALAM')
l3.pack()
c2=tkinter.Checkbutton(win,variable=v2)
c2.pack()
l4=tkinter.Label(text='Hindi')
l4.pack()
c3=tkinter.Checkbutton(win,variable=v3)
c3.pack()
b2=tkinter.Button(win,text='check',command=data2)
b2.pack()
win.mainloop()